CREATE TABLE TAB_PURCHASE (
    CODG_TRANSACTION INT AUTO_INCREMENT PRIMARY KEY,
    DATE_TRANSACTION TIMESTAMP NOT NULL,
    PURCHASE_AMOUNT FLOAT NOT NULL,
    DESCRIPTION VARCHAR(50)
);

-- Information to populate and test the database
INSERT INTO TAB_PURCHASE (CODG_TRANSACTION, DATE_TRANSACTION, PURCHASE_AMOUNT, DESCRIPTION)
VALUES (1, '2023-09-11 10:00:00', 100.0, 'CIGARRETS');

INSERT INTO TAB_PURCHASE (CODG_TRANSACTION, DATE_TRANSACTION, PURCHASE_AMOUNT, DESCRIPTION)
VALUES (2, '2023-09-06 14:30:00', 150.0, 'MILK HAPPY COW');

INSERT INTO TAB_PURCHASE (CODG_TRANSACTION, DATE_TRANSACTION, PURCHASE_AMOUNT, DESCRIPTION)
VALUES (3, '2023-09-07 09:15:00', 75.0, 'BREAD');